# Generated by Django 4.1.2 on 2023-07-18 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_alter_walletlistdb_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='walletlistdb',
            old_name='famale',
            new_name='female',
        ),
    ]
