# Generated by Django 4.1.2 on 2023-07-18 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingOtherDb',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('product', models.CharField(max_length=180)),
                ('done', models.BooleanField(blank=True, default=False)),
            ],
        ),
    ]
