# Generated by Django 4.1.2 on 2023-07-17 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colordb',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
