# Generated by Django 4.1.2 on 2023-06-29 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingList',
            fields=[
                ('auto_increment_id', models.AutoField(primary_key=True, serialize=False)),
                ('data_time', models.DateTimeField(auto_now_add=True)),
                ('things_to_buy', models.CharField(max_length=300)),
                ('checked', models.BooleanField()),
                ('finished', models.BooleanField()),
            ],
        ),
    ]
